version: '3.3'

services:
  post_db:
    # env_file:
    #   - variables.env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back:
        aliases:
          - post_db
          - comment_db
  ui:
    # env_file:
    #   - variables.env
    # build: ./ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${DOCKERUSER}/ui:${UI_VER}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    # env_file:
    #   - variables.env
    # build: ./post-py
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${DOCKERUSER}/post:${POST_VER}
    networks:
      back:
        aliases:
          - post
      front:
        aliases:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    # env_file:
    #   - variables.env
    # build: ./comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${DOCKERUSER}/comment:${COMMENT_VER}
    networks:
      back:
        aliases:
          - comment
      front:
        aliases:
          - comment
  prometheus:
    image: ${DOCKERUSER}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back
      - front

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back

volumes:
  post_db:
  prometheus_data:

networks:
  back:
  front:
